// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.nordicstorm.robotics.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;
import org.nordicstorm.robotics.Robot;
import org.nordicstorm.robotics.RobotMap;

/**
 *
 */
public class DriveRobot extends CommandGroup {
    
    public  DriveRobot() {

        requires(Robot.driveTrain);
        if (RobotMap.driveTrain_leftRearMotor != null){
            addSequential(new DriveArcade());
            addSequential(new DriveTwist());
            addSequential(new DriveTank());
        }
    }
    
    public static double getDeadZone(double value, double deadzone){
        if (Math.abs(value) < deadzone){
            return 0;
        }else{
            return value;
        }
    }
    
    public static double checkInverted(double value, boolean inverted){
        if (inverted){
           return -value;
        }else{
           return value;
        }
    }
}
