// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc3018.BetaTest1.commands;
import org.usfirst.frc3018.BetaTest1.parseextension.ParsableCommand;
/**
 *
 */
public class  AutonomousTest4 extends ParsableCommand {
    private String _output = "";
    private boolean _ran = false;
    
    public AutonomousTest4(String output) {
        _output= output;
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    public AutonomousTest4(){
        _output = "No argument set!";
    }
    
    // Called just before this Command runs the first time
    protected void initialize() {
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        _ran = true;
        System.out.println(_output);
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return _ran;
    }
    // Called once after isFinished returns true
    protected void end() {
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
    public String getName() {
        return("AutoTest4");
    }
    public String getIdentifier() {
        return("d");
    }
    public void setArguments(String[] args) {
        _output = args[0];
    }
}
